export const ACTIVITY_TYPES: readonly string[] = [
  'hiking',
  'modern architecture',
  'modern art museums',
  'classic famous places',
  "food halls and farmers' markets",
  'classic architecture and history',
  'cool hotels',
  'nightclubs',
  'kayaking',
  'biking',
  'running',
  'gym',
  'boutique shopping',
  'vintage markets',
  'street art exploration',
  'rooftop bars',
  'live music venues',
  'jazz clubs',
  'wine bars and tasting rooms',
  'brewery visits',
  'guided food tours',
  'cooking classes',
  'design and furniture stores',
  'spa and wellness experiences',
  'river walks and waterfronts',
  'scenic viewpoints',
  'cultural festivals',
  'pop-up events',
  'co-working spaces',
  'local neighborhood exploration',
] as const;
