export const DRINK_STYLES: readonly string[] = [
  'craft beer',
  'funky and cloudy natural orange wine',
  'pét-nats',
  'champagne',
  'oxidated wines',
  'sherrys',
  'new world white wines',
  'old world white wines',
  'new world red wines',
  'old world red wines',
  'dessert wines',
  'long classic cocktails',
  'funky craft short cocktails',
  'juices',
  'tea',
  'craft espressos',
  'fast food coffee',
  'natural red wines',
  'skin-contact whites',
  'vermouths and aromatized wines',
  'amaro and bitters',
  'sake',
  'mezcal and tequila',
  'whisky and bourbon',
  'low-ABV cocktails',
  'alcohol-free craft drinks',
  'specialty filter coffee',
  'cold brew coffee',
  'kombucha and fermented drinks',
  'aperitivo-style spritzes',
] as const;
