export const FOOD_STYLES: readonly string[] = [
  'raw tartars',
  'raw seafood',
  'funky vegetables',
  'local traditional specialties',
  'local modern fusion dishes',
  'craft desserts',
  'hearty soups',
  'rich salads',
  'steaks',
  'fast food',
  'modern Asian fusion',
  'classic French',
  'Italian',
  'tapas dishes',
  'Latin America',
  'modern local Nordic food',
  'wood-fired cuisine',
  'nose-to-tail/offal dishes',
  'fermented foods',
  'plant-forward fine dining',
  'street food specialties',
  'seafood grills',
  'sushi and omakase',
  'dumplings and dim sum',
  'ramen and noodle bowls',
  'BBQ and smoked meats',
  'seasonal tasting menus',
  'cheese-focused dishes',
  'bakery and pastry specialties',
  'late-night comfort food',
] as const;
