export const EAT_SOURCES = [
  'Michelin Guide',
  "The World's 50 Best Restaurants",
  'Gambero Rosso',
  'La Liste',
  'Eater',
  'Time Out',
  'Infatuation',
  'Tripadvisor',
  'Google Maps',
  'Yelp',
  'OpenTable',
  'Resy',
  'Star Wine List',
  'Opinionated About Dining',
  'Bloomberg Food & Drink',
] as const;

export const DRINK_SOURCES = [
  'Raisin',
  'Vivino',
  'Decanter',
  'Wine Spectator',
  'Wine Enthusiast',
  'CellarTracker',
  'Untappd',
  'RateBeer',
  "The World's 50 Best Bars",
  'Top 500 Bars',
  "Difford's Guide",
  'Punch',
  'Liquor.com',
  'Wine-Searcher',
  'GuildSomm',
  'Sprudge',
  'Perfect Daily Grind',
  'European Coffee Trip',
  'World Coffee Events',
  'Beanhunter',
  'Foursquare',
  'Google Maps',
  'Instagram',
  'TikTok',
  'Barista Magazine',
  'Standart Magazine',
  'Eater Coffee',
  'Time Out',
] as const;

export const DO_SOURCES = [
  'Lonely Planet',
  'Condé Nast Traveler',
  'National Geographic Travel',
  'Atlas Obscura',
  'Google Maps',
  'Tripadvisor',
  'GetYourGuide',
  'Viator',
  'Time Out',
  'Airbnb',
  'Rick Steves Europe',
  'Culture Trip',
  'Design Hotels',
  'Wallpaper* City Guides',
  'Wikipedia',
] as const;
