// Curated reference-source lists per category. These are the names Claude
// is instructed to draw from when curating expert picks AND when enriching
// individual places for the detail pop-up. Order roughly reflects "inner
// circle" weight — the first ~10 of each list carry the most cred among
// serious food/drink/culture travellers right now.

export const EAT_SOURCES = [
  'World of Mouth',
  "The World's 50 Best Restaurants / 50 Best Discovery",
  'MICHELIN Guide',
  'Raisin',
  'Opinionated About Dining (OAD)',
  'Gault&Millau',
  'Star Wine List',
  'Le Fooding',
  'La Liste',
  'Gambero Rosso',
  'Identità Golose',
  'Eater',
  'Punch',
  'The Infatuation',
  'Time Out Eat & Drink',
  'Bloomberg Food & Drink',
  'Monocle Travel Guides',
  'Kinfolk City Guides',
  'MAD Feed / Noma Projects',
  'Condé Nast Traveler Restaurants',
  'Food & Wine Best Restaurants',
  'Bon Appétit Restaurants',
  'Fine Dining Lovers',
  'Italy Segreta',
  'Scatti di Gusto',
  'Dissapore',
  'Very Good Lord',
  'Beli',
  'Tabelog',
  'OpenTable',
  'Resy',
  'Yelp',
  'Google Maps',
  'HappyCow',
  'Untappd',
  'RateBeer',
  'Vivino',
  'CellarTracker',
  'Reddit r/finedining',
  'Tripadvisor',
] as const;

export const DRINK_SOURCES = [
  "The World's 50 Best Bars",
  'Top 500 Bars',
  'World of Mouth',
  'Raisin',
  'Star Wine List',
  'Opinionated About Dining (OAD)',
  'MICHELIN Guide',
  'Le Fooding',
  'Punch',
  'VinePair',
  "Difford's Guide",
  'Gault&Millau',
  'Gambero Rosso',
  'Identità Golose',
  'CellarTracker',
  'Vivino',
  'Untappd',
  'RateBeer',
  'BeerAdvocate',
  'The Infatuation',
  'Eater',
  'Condé Nast Traveler Eat & Drink',
  'Food & Wine Global Tastemakers',
  'Bon Appétit Restaurants & Bars',
  'La Liste',
  'Time Out Bars & Restaurants',
  'Italy Segreta',
  'Dissapore',
  'Scatti di Gusto',
  'Beli',
  'Tabelog',
  'Resy',
  'OpenTable',
  'Yelp',
  'Google Maps',
  'Reddit r/cocktails',
  'Reddit r/wine',
  'Reddit r/CraftBeer',
  'Seeker Social',
  'Tripadvisor',
] as const;

export const DO_SOURCES = [
  'World of Mouth',
  'Atlas Obscura',
  'Google Arts & Culture',
  'Wanderlog',
  'Komoot',
  'Roadtrippers',
  'Culture Trip',
  'Monocle Travel Guides',
  'Kinfolk City Guides',
  'Spotted by Locals',
  'Use-It Travel Guides',
  'Wallpaper* City Guides',
  'Condé Nast Traveler',
  'Cool Cousin',
  'Foursquare City Guide',
  'Airbnb Experiences',
  'GetYourGuide',
  'Viator',
  'Withlocals',
  'GuruWalk',
  'AllTrails',
  'Outdooractive',
  'The Outbound',
  'Google Maps',
  'Yelp',
  'Beli',
  'TripIt',
  'Polarsteps',
  'Lonely Planet',
  'Time Out',
  'Secret Media Network',
  'Booking.com',
  'Design Hotels',
  'Mr & Mrs Smith',
  'Tablet Hotels',
  'Tripadvisor',
  'Rome2Rio',
  'Maps.me',
  'Reddit Travel Communities',
  'TikTok Travel',
] as const;
